{% set name = "lmfit" %}
{% set version = "0.8.3" %}
{% set sha256 = "b34250e48172ff4d84ecb8200da4afa43376bc1ae49c7ddf70b7a4670127440a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - {{ name }}

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  license_file: LICENSE
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/
