{% set name = "lmfit" %}
{% set version = "0.9.13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-py/archive/{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: b604afca0aaa23b28170065853b59d6e4c585c367e537b769813af313f8ebeed

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - asteval>=0.9.11
    - numpy
    - scipy>=0.17
    - six
    - uncertainties>=3.0

test:
  imports:
    - {{ name }}

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  license_file: LICENSE
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/
