{% set name = "lmfit" %}
{% set version = "0.8.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-py/archive/{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: cb96919efe57e800cec3187edb88fb8c4aecd0b5687f7fd9d6e4bd10f746880a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - {{ name }}

about:
  home: http://lmfit.github.io/lmfit-py/
  license: lmfit
  license_family: BSD
  license_file: LICENSE
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - newville
    - danielballan
